# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    build: ./db
    # image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    volumes:
      - ./datadir:/var/lib/mysql

  adminer:
    build: ./adminer
    # image: adminer
    restart: always
    ports:
      - 6080:8080
